name: CI

on:
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  display:
    runs-on: ubuntu-latest
    env:
      NOTION_SECRET_KEY: ${{ secrets.NOTION_SECRET_KEY }}


    steps:
      - name: Display Notion secret key
        run: |
          echo "Notion Secret Key: ${{ env.NOTION_SECRET_KEY }}"
