name: CI

on:
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  display:
    runs-on: ubuntu-latest
    env:
      test_secret: Some kind of secret

    steps:
      - name: Display the test secret
      run: |
        echo "Secret value ${{ env.test_secret }}"
